### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by smarquez1**
Add deoplete.nvim configuration

### CODE REVIEW

**Comment by linduxed** [comment]
This would need a mention that it breaks if one does not have `vimproc.vim` installed.

**Comment by smarquez1** [comment]
vimproc is already mentioned as a requirement on top of the codeblock

**Comment by linduxed** [comment]
Ah, yes, this is true.

**Comment by osyo-manga** [comment]
Oh, sorry.
Thank you pull request!!

**Comment by stevinus73** [comment]
oh yes

**Pull request merged**
